### ISSUE TITLE
Error when running in CI/CD - GitHub Actions

### ISSUE THREAD

**Issue by rlinstorres** [yuvipanda/pre-commit-hook-ensure-sops#22]
Hi, there!

We are trying to implement this hook in our projects and it's working locally when pushing commits but when running in CI/CD, we are getting an error but the error message is not clear about what is the problem.

Our settings:

```yaml
repos:
  - repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
    rev: v1.1
    hooks:
      - id: sops-encryption
```

Running Locally:

![Screenshot 2023-09-15 at 10 21 52 AM](https://github.com/yuvipanda/pre-commit-hook-ensure-sops/assets/11336131/b8449d2a-1fc5-4296-acd5-4604d62d0b63)

Running in CI/CD:

<img width="635" alt="Screenshot 2023-09-15 at 10 48 55 AM" src="https://github.com/yuvipanda/pre-commit-hook-ensure-sops/assets/11336131/a3f7b1cd-48f1-499a-ac76-cc13ddc7d967">

This is the log:

```
Ensure secrets are encrypted with sops...................................Failed
- hook id: sops-encryption
- exit code: 1

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/.cache/pre-commit/repoqi7m9v0g/py_env-python3/lib/python3.10/site-packages/pre_commit_hook_ensure_sops/__main__.py", line 97, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repoqi7m9v0g/py_env-python3/lib/python3.10/site-packages/pre_commit_hook_ensure_sops/__main__.py", line [85](https://github.com/FindHotel/cloud-platform-modules/actions/runs/6195858319/job/16821365826#step:5:89), in main
    is_valid, message = check_file(f)
  File "/home/runner/.cache/pre-commit/repoqi7m9v0g/py_env-python3/lib/python3.10/site-packages/pre_commit_hook_ensure_sops/__main__.py", line 53, in check_file
    doc = loader_func(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/.cache/pre-commit/repoqi7m9v0g/py_env-python3/lib/python3.10/site-packages/pre_commit_hook_ensure_sops/__main__.py", line 97, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repoqi7m9v0g/py_env-python3/lib/python3.10/site-packages/pre_commit_hook_ensure_sops/__main__.py", line 85, in main
    is_valid, message = check_file(f)
  File "/home/runner/.cache/pre-commit/repoqi7m9v0g/py_env-python3/lib/python3.10/site-packages/pre_commit_hook_ensure_sops/__main__.py", line 53, in check_file
    doc = loader_func(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by yuvipanda** [comment]
Do you have a view of the file this error is failing with? Or even the name of the file? It looks like we're trying to read as json something that isn't json

**Comment by rlinstorres** [comment]
> Do you have a view of the file this error is failing with? Or even the name of the file? It looks like we're trying to read as json something that isn't json

Hi @yuvipanda, that's strange because we are not using json files, this is our local setting in terragrunt:

```
secrets = yamldecode(sops_decrypt_file(find_in_parent_folders("secret.yaml")))
```

I'm trying to figure out what is happening by doing some tests.

**Comment by nialov** [comment]
A minimal example of the file in question is required to debug this I believe! I can also debug the issue if it is provided.

**Comment by zoechi** [comment]
I just run into this error. 

```
pre-commit-hook-ensure-sops..............................................Failed
- hook id: pre-commit-hook-ensure-sops
- exit code: 1

Traceback (most recent call last):
  File "/nix/store/w5g6vwac3i3a0jl8p0adrhbn7110l13b-pre-commit-hook-ensure-sops-1.1/bin/.pre-commit-hook-ensure-sops-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/w5g6vwac3i3a0jl8p0adrhbn7110l13b-pre-commit-hook-ensure-sops-1.1/lib/python3.12/site-packages/pre_commit_hook_ensure_sops/__main__.py", line 85, in main
    is_valid, message = check_file(f)
                        ^^^^^^^^^^^^^
  File "/nix/store/w5g6vwac3i3a0jl8p0adrhbn7110l13b-pre-commit-hook-ensure-sops-1.1/lib/python3.12/site-packages/pre_commit_hook_ensure_sops/__main__.py", line 53, in check_file
    doc = loader_func(f)
          ^^^^^^^^^^^^^^
  File "/nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/lib/python3.12/json/decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I had a (cargo script) `genkey.rs` file in the `secrets/hosts/` directory. After I moved it out, the error went away.
